controller_list:
  - name: arm_1/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5

      
# the followings are added for tuning trajectory following. Added by tianbao, 14.12.2016
    constraints:
      goal_time: 2                   # Override default
      arm_joint_1:
        trajectory: 0.001               # Not enforced if unspecified
        goal: 0.001                     # Not enforced if unspecified
      arm_joint_2:
        trajectory: 0.001               # Not enforced if unspecified
        goal: 0.001                     # Not enforced if unspecified
      arm_joint_3:
        trajectory: 0.01               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      arm_joint_4:
        trajectory: 0.01               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      arm_joint_5:
        trajectory: 0.01               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
    gains: # arm_joint_1 have large overshot. Therefore tune it manually
      arm_joint_1: {p: 100, i: 1, d: 0,  i_clamp: 1000}
      arm_joint_2: {p: 110, i: 2, d: 2,  i_clamp: 1000}